name: Enum Compatibility Test
on: [pull_request]

jobs:
  enum-compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Install dotnet-script
        run: dotnet tool install -g dotnet-script

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.x"

      - name: Run C# Serializer
        working-directory: enum_compatibility_test
        run: dotnet script serialize_enums.csx > csharp_enum_output.json

      - name: Run Go Deserializer Test
        working-directory: enum_compatibility_test
        run: go test -v ./...
